"""Add autoincrement to id

Revision ID: 17e15f4fbe2b
Revises: 5136b49515a2
Create Date: 2023-07-24 16:33:12.438538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e15f4fbe2b'
down_revision = '5136b49515a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
