"""change driver psycopg -> asyncpg

Revision ID: 5136b49515a2
Revises: 1448643a4310
Create Date: 2023-07-24 15:15:15.660619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5136b49515a2'
down_revision = '1448643a4310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
